cursor #dfe5d2
cursor_text_color #c3c9b7

foreground            #dfe5d2
background            #10150a
selection_foreground  #1c361d
selection_background  #afcfab
url_color             #87dd00

color0   #10150a
color1   #fe2a00
color2   #11dd00
color3   #ffdb00
color4   #80d100
color5   #3e6600
color6   #87dd00
color7   #dde8cc
color8   #878f7a
color9   #ff5f3f
color10  #5aff4c
color11  #ffe64c
color12  #a2f324
color13  #b9ff4c
color14  #d2ff8c
color15  #fafff2
