cursor #e1e4da
cursor_text_color #c3c8bc

foreground            #e1e4da
background            #11140f
selection_foreground  #273421
selection_background  #bccbb1
url_color             #a7d394

color0   #11140f
color1   #f2886d
color2   #6ed369
color3   #ffed72
color4   #96c880
color5   #3c612c
color6   #a7d394
color7   #d4ddd0
color8   #81897e
color9   #ffb29f
color10  #a8fda4
color11  #fff3a5
color12  #bee8ad
color13  #d9ffc9
color14  #e7ffdc
color15  #fafff8
